### ISSUE TITLE
Add keepalive using GitHub actions API

### ISSUE THREAD

**Issue by gautamkrishnar** [gautamkrishnar/keepalive-workflow#22]
Now GitHub supports re-enabling the workflows using GitHub API. 

```sh
gh api -X PUT repos/{ repo }/actions/workflows/{ actionFile }/enable
```
### ToDo
- [ ] Provide API for action developers to use this approach
- [ ] Add this as an option to the keepalive workflow
- [ ] Switch to the new approach in the future as the default method

ref: #1

**Comment by gautamkrishnar** [comment]
@all-contributors please add @liskin for ideas
